code/external/02/config/routes.rb
#---
# Excerpted from "Rails 5 Test Prescriptions",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrtest3 for more book information.
#---
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"

  resources :tasks do
    member do
      patch :up
      patch :down
    end
  end

  resources :projects
end

code/external/02/app/models/project.rb
#---
# Excerpted from "Rails 5 Test Prescriptions",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrtest3 for more book information.
#---
class Project < ApplicationRecord

  include Sizeable

  #
  has_many :roles
  has_many :users, through: :roles
  #

  has_many :tasks, -> { order "project_order ASC" }

  validates :name, presence: true

  #
  def self.all_public
    where(public: true)
  end
  #

  def self.velocity_length_in_days
    21
  end

  def incomplete_tasks
    tasks.reject(&:complete?)
  end

  def done?
    incomplete_tasks.empty?
  end

  def size
    tasks.sum(&:size)
  end

  def remaining_size
    incomplete_tasks.sum(&:size)
  end

  def completed_velocity
    tasks.sum(&:points_toward_velocity)
  end

  def current_rate
    completed_velocity * 1.0 / Project.velocity_length_in_days
  end

  def projected_days_remaining
    remaining_size / current_rate
  end

  def on_schedule?
    return false if projected_days_remaining.infinite?
    return false if projected_days_remaining.nan?
    (Date.today + projected_days_remaining) <= due_date
  end

  #
  def next_task_order
    return 1 if tasks.empty?
    (tasks.last.project_order || tasks.size) + 1
  end
  #

end

code/external/02/app/controllers/projects_controller.rb
#---
# Excerpted from "Rails 5 Test Prescriptions",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrtest3 for more book information.
#---
class ProjectsController < ApplicationController

  #
  def show
    @project = Project.find(params[:id])
    unless current_user.can_view?(@project)
      redirect_to new_user_session_path
      return
    end
    respond_to do |format|
      format.html {}
      format.js { render json: @project.as_json(root: true, include: :tasks) }
    end
  end
  #

  def new
    @project = Project.new
  end

  #
  def index
    @projects = current_user.visible_projects
  end
  #

  #
  def create
    @workflow = CreatesProject.new(
        name: params[:project][:name],
        task_string: params[:project][:tasks],
        users: [current_user])
    @workflow.create
    if @workflow.success?
      redirect_to projects_path
    else
      @project = @workflow.project
      render :new
    end
  end
  #

end

code/external/02/app/helpers/projects_helper.rb
#---
# Excerpted from "Rails 5 Test Prescriptions",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrtest3 for more book information.
#---
module ProjectsHelper
  def name_with_status(project)
    dom_class = project.on_schedule? ? "on_schedule" : "behind_schedule"
    content_tag(:span, project.name, class: dom_class)
  end
end

code/external/02/app/views/projects/index.html.erb
<h1>All Projects</h1>
<table>
  <thead>
    <tr>
      <td>Project Name</td>
      <td>Total Project Size</td>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr class="project-row" id="<%= dom_id(project) %>">
        <td class="name"><%= name_with_status(project) %></td>
        <td class="total-size"><%= project.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

code/external/02/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for(@project) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <br />
  <%= f.label(:tasks) %>
  <%= text_area_tag("project[tasks]") %>
  <br />
  <%= f.submit %>
<% end %>

code/external/02/app/views/projects/show.html.erb
<h2>Project <%= @project.name %></h2>

<h3>Existing Tasks:</h3>

<div>
  <table>
    <thead>
      <tr>Name</tr>
      <tr>Size</tr>
    </thead>
    <tbody>
      <% @project.tasks.each do |task| %>
        <tr id="task_<%= task.project_order %>">
          <td class="name"><%= task.title %></td>
          <td class="size"><%= task.size %></td>
          <td class="completed">
            <% if task.complete? %>
              <%= task.user.email %>
              <%= task.completed_at.to_s %>
              <img src="<%= task.user.avatar_url %>" />
            <% end %>
          </td>
          <td>
            <% unless task.first_in_project? %>
              <%= link_to "Up", up_task_path(task.id), method: :patch %>
            <% end %>
            <% unless task.last_in_project? %>
              <%= link_to "Down", down_task_path(task.id), method: :patch %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h3>New Task</h3>

<%= form_for Task.new(project_id: @project.id) do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.label :title, "Task" %>
  <%= f.text_field :title %>
  <%= f.label :size %>
  <%= f.select :size, [1, 2, 3, 4, 5] %>
  <%= f.submit "Add Task" %>
<% end %>